#ifndef PLAYER_ANIMATION_H
#define PLAYER_ANIMATION_H

#define ANIMATION_WALK_INIT "A"
#define ANIMATION_WALK_END "D"

#define ANIMATION_SHOOT_INIT "E"
#define ANIMATION_SHOOT_END "F"

#define ANIMATION_DEATH_INIT "G"
#define ANIMATION_DEATH_END "N"

#define ANIMATION_EXTREME_DEATH_INIT "O"
#define ANIMATION_EXTREME_DEATH_END "W"

extern char ANIMATION_NAME[8];

#endif